services:
  db:
    image: postgres:15
    container_name: propel_db
    restart: always
    environment:
      POSTGRES_USER: propel
      POSTGRES_PASSWORD: propelpass
      POSTGRES_DB: propel_eval
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U propel -d propel_eval" ]
      interval: 5s
      timeout: 5s
      retries: 10
